package scorebj.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CompetitionForm {
    private JFrame frame = new JFrame("Scoring Bill Jones");

    private JPanel topLevelPanel;
    private JComboBox<String> competitionNameComboBox;
    private JTextField noSets;
    private JTextField noBoardsPerSetField;
    private JLabel noOfSetsLabel;
    private JLabel noOfBoardsPerLabel;
    private JTextField dateField;
    private JLabel competitionNameLabel;
    private JLabel dateLabel;
    private JButton OKButton;

    public CompetitionForm() {
        $$$setupUI$$$();
        OKButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });
        competitionNameComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if ("comboBoxEdited".equals(e.getActionCommand())) {
                    JComboBox<String> comboBox = (JComboBox<String>) e.getSource();
                    String selection = (String) comboBox.getSelectedItem();

                    comboBox.removeItem(selection);
                    comboBox.addItem(selection);

                } else {
                    if ("comboBoxChange".equals(e.getActionCommand())) {

                    }

                }

            }
        });
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        competitionNameComboBox = new JComboBox<>();
    }

    public void setData(CompetitionFormBean data) {
        noSets.setText(data.getNoSets());
        noBoardsPerSetField.setText(data.getCompetitionName());
        dateField.setText(data.getDate());
    }

    public void getData(CompetitionFormBean data) {
        data.setNoSets(noSets.getText());
        data.setCompetitionName(noBoardsPerSetField.getText());
        data.setDate(dateField.getText());
    }

    public void display() {

        frame.setContentPane(this.topLevelPanel);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        //Center the window
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = new Dimension(580, 700);
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        //frame.add(new SuDoQForm());
        frame.setLocation((screenSize.width - frameSize.width) / 2, (screenSize.height - frameSize.height) / 2);
        frame.pack();
        frame.setVisible(true);

    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        topLevelPanel = new JPanel();
        topLevelPanel.setLayout(new GridBagLayout());
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topLevelPanel.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.VERTICAL;
        topLevelPanel.add(spacer2, gbc);
        noSets = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topLevelPanel.add(noSets, gbc);
        noBoardsPerSetField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topLevelPanel.add(noBoardsPerSetField, gbc);
        noOfSetsLabel = new JLabel();
        noOfSetsLabel.setText("No of Sets");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        topLevelPanel.add(noOfSetsLabel, gbc);
        noOfBoardsPerLabel = new JLabel();
        noOfBoardsPerLabel.setText("No of Boards per Set");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        topLevelPanel.add(noOfBoardsPerLabel, gbc);
        competitionNameComboBox.setEditable(true);
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topLevelPanel.add(competitionNameComboBox, gbc);
        dateField = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topLevelPanel.add(dateField, gbc);
        competitionNameLabel = new JLabel();
        competitionNameLabel.setText("Competition Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        topLevelPanel.add(competitionNameLabel, gbc);
        dateLabel = new JLabel();
        dateLabel.setText("Date");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        topLevelPanel.add(dateLabel, gbc);
        OKButton = new JButton();
        OKButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        topLevelPanel.add(OKButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return topLevelPanel;
    }

}
