package scorebj.gui;

import javax.swing.*;
import java.awt.*;

public class PairingForm {
    private JList pairList;
    private JPanel mainPanel;
    private JList playerList;
    private JScrollPane playerListPanel;
    private JPanel addPanel;
    private JPanel buttonPanel;
    private JPanel pairListPanel;
    private JButton ADDButton;
    private JButton REMOVEButton;
    private JButton ENTERButton;
    private JTextField newPlayerField;
    private JButton DELETEButton;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridBagLayout());
        mainPanel.setEnabled(false);
        playerListPanel = new JScrollPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(playerListPanel, gbc);
        playerList = new JList();
        playerListPanel.setViewportView(playerList);
        addPanel = new JPanel();
        addPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(addPanel, gbc);
        pairListPanel = new JPanel();
        pairListPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(pairListPanel, gbc);
        pairList = new JList();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        pairListPanel.add(pairList, gbc);
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.TRAILING, 5, 5));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 3;
        gbc.fill = GridBagConstraints.BOTH;
        mainPanel.add(buttonPanel, gbc);
        newPlayerField = new JTextField();
        buttonPanel.add(newPlayerField);
        ENTERButton = new JButton();
        ENTERButton.setText("ENTER");
        buttonPanel.add(ENTERButton);
        DELETEButton = new JButton();
        DELETEButton.setText("DELETE");
        buttonPanel.add(DELETEButton);
        ADDButton = new JButton();
        ADDButton.setText("ADD");
        buttonPanel.add(ADDButton);
        REMOVEButton = new JButton();
        REMOVEButton.setText("REMOVE");
        buttonPanel.add(REMOVEButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
